name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Build
      run: |
        xcodebuild build -project a.xcodeproj -scheme a clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

    - name: Run tests
      run: |
        xcodebuild test -project a.xcodeproj -scheme a clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No
